### ISSUE TITLE
a very big question

### ISSUE THREAD

**Issue by darkx239** [StylexTV/LYNX#2]
I would love to donate tons of money if this project is going to be long term like baritone where it gets updates regularly

**Comment by darkx239** [comment]
Also forgot to add is this like a forge or fabric mod or something its kinda unclear to me

**Comment by StylexTV** [comment]
Wow that is a big question xD

I do plan to work on this project for a long time, but only as a hobby, so financial support is neither necessary nor motivating. Also, paying for the development of this project would make me feel like I have to work on it even if I sometimes don't have time or don't feel like programming.
However, since this project is still very young, I am the only developer at the moment, and since it is an open source project, I hope that other developers will join over time. Maybe they would be happy to get some money for their work.

Anyway, thank you for even wanting to support my work financially :)
